import path from 'path';
import type { ErrorPattern } from '../core/types.js';
import { CLAUDE_DIR, RULES_DIR } from '../core/constants.js';
import { writeFileAtomic } from '../utils/fs.js';

/**
 * Generate a .claude/rules/learned/*.md file from an error pattern.
 * Returns the path of the generated file.
 */
export async function generateRuleFromPattern(
  projectRoot: string,
  pattern: ErrorPattern,
): Promise<string> {
  const filename = `${pattern.id}.md`;
  const filePath = path.join(projectRoot, CLAUDE_DIR, RULES_DIR, 'learned', filename);

  const content = formatRuleContent(pattern);
  await writeFileAtomic(filePath, content);

  return filePath;
}

/**
 * Format a rule file from an error pattern.
 */
export function formatRuleContent(pattern: ErrorPattern): string {
  const lines: string[] = [];

  lines.push('---');
  lines.push(`description: "Auto-generated rule from error pattern: ${pattern.description}"`);
  lines.push(`globs: "**/*"`);
  lines.push('---');
  lines.push('');
  lines.push(`# ${pattern.description}`);
  lines.push('');
  lines.push(`> Auto-generated by diverger-claude from ${pattern.occurrences} occurrences of this error pattern.`);
  lines.push('');
  lines.push('## Problem');
  lines.push('');
  lines.push(`This error has been observed ${pattern.occurrences} times (category: \`${pattern.category}\`${pattern.tool ? `, tool: \`${pattern.tool}\`` : ''}).`);
  lines.push('');
  lines.push(`Pattern: \`${pattern.matchPattern}\``);
  lines.push('');

  if (pattern.resolution) {
    lines.push('## Resolution');
    lines.push('');
    lines.push(pattern.resolution);
    lines.push('');
  }

  lines.push('## Stats');
  lines.push('');
  lines.push(`- First seen: ${pattern.firstSeen}`);
  lines.push(`- Last seen: ${pattern.lastSeen}`);
  lines.push(`- Occurrences: ${pattern.occurrences}`);
  lines.push('');

  return lines.join('\n');
}
