import type { ComposedConfig, GeneratedFile } from '../../core/types.js';
import { CLAUDE_DIR, CLAUDE_MD } from '../../core/constants.js';
import path from 'path';

/** Generate the .claude/CLAUDE.md file from composed config */
export function generateClaudeMd(
  config: ComposedConfig,
  projectRoot: string,
): GeneratedFile {
  const sections = [...config.claudeMdSections].sort((a, b) => a.order - b.order);

  const parts: string[] = [
    '# Project Configuration',
    '',
    `> Generated by diverger-claude. Applied profiles: ${config.appliedProfiles.join(', ')}`,
    '',
  ];

  for (const section of sections) {
    parts.push(section.content);
    parts.push('');
  }

  return {
    path: path.join(projectRoot, CLAUDE_DIR, CLAUDE_MD),
    content: parts.join('\n'),
  };
}
