import type { ComposedConfig, DetectionResult, GeneratedFile, ProjectMetadata } from '../../core/types.js';
import { CLAUDE_MD } from '../../core/constants.js';
import path from 'path';

/** Build the "About This Project" section from metadata */
function buildProjectContext(metadata: ProjectMetadata): string | null {
  if (!metadata.name && !metadata.description && !metadata.readmeSummary && metadata.keyDirectories.length === 0) {
    return null;
  }

  const lines: string[] = [];
  lines.push('## About This Project');
  lines.push('');

  if (metadata.name) {
    lines.push(`**${metadata.name}**${metadata.description ? ` — ${metadata.description}` : ''}`);
    lines.push('');
  } else if (metadata.description) {
    lines.push(metadata.description);
    lines.push('');
  }

  if (metadata.readmeSummary && metadata.readmeSummary !== metadata.description) {
    lines.push(metadata.readmeSummary);
    lines.push('');
  }

  if (metadata.architecture) {
    lines.push(`**Architecture:** ${metadata.architecture}`);
    lines.push('');
  }

  if (metadata.keyDirectories.length > 0) {
    lines.push('**Key directories:**');
    for (const dir of metadata.keyDirectories) {
      lines.push(`- \`${dir}/\``);
    }
    lines.push('');
  }

  lines.push('<!-- Add more project-specific context: architecture decisions, dev workflow, deployment, etc. -->');

  return lines.join('\n');
}

/** Build the "Available Commands" section from scripts metadata */
function buildCommandsSection(metadata: ProjectMetadata): string | null {
  const lines: string[] = [];

  const hasNpmScripts = metadata.scripts && Object.keys(metadata.scripts).length > 0;
  const hasPythonScripts = metadata.pythonScripts && Object.keys(metadata.pythonScripts).length > 0;
  const hasMakeTargets = metadata.makeTargets && metadata.makeTargets.length > 0;

  if (!hasNpmScripts && !hasPythonScripts && !hasMakeTargets) return null;

  lines.push('## Available Commands');
  lines.push('');

  const pm = metadata.packageManager ?? 'npm';

  if (hasNpmScripts) {
    for (const [key, value] of Object.entries(metadata.scripts!)) {
      lines.push(`- \`${pm} run ${key}\` — ${value}`);
    }
  }

  if (hasPythonScripts) {
    for (const [key, value] of Object.entries(metadata.pythonScripts!)) {
      lines.push(`- \`${key}\` — ${value}`);
    }
  }

  if (hasMakeTargets) {
    for (const target of metadata.makeTargets!) {
      lines.push(`- \`make ${target}\``);
    }
  }

  return lines.join('\n');
}

/** Build the "Entry Points" section from metadata */
function buildEntryPointsSection(metadata: ProjectMetadata): string | null {
  if (!metadata.entryPoints || Object.keys(metadata.entryPoints).length === 0) return null;

  const lines: string[] = [];
  lines.push('## Entry Points');
  lines.push('');

  for (const [name, entryPath] of Object.entries(metadata.entryPoints)) {
    lines.push(`- **${name}**: \`${entryPath}\``);
  }

  return lines.join('\n');
}

/** Generate the CLAUDE.md file at the project root */
export function generateClaudeMd(
  config: ComposedConfig,
  projectRoot: string,
  _detection?: DetectionResult,
  metadata?: ProjectMetadata,
): GeneratedFile {
  const sections = [...config.claudeMdSections].sort((a, b) => a.order - b.order);

  const parts: string[] = [
    '# Project Configuration',
    '',
    `> Generated by diverger-claude. Applied profiles: ${config.appliedProfiles.join(', ')}`,
    `> For personal overrides, create \`CLAUDE.local.md\` (gitignored).`,
    '',
  ];

  // Project context section (from metadata)
  if (metadata) {
    const projectContext = buildProjectContext(metadata);
    if (projectContext) {
      parts.push(projectContext);
      parts.push('');
    }

    // Available Commands section
    const commandsSection = buildCommandsSection(metadata);
    if (commandsSection) {
      parts.push(commandsSection);
      parts.push('');
    }

    // Entry Points section
    const entryPointsSection = buildEntryPointsSection(metadata);
    if (entryPointsSection) {
      parts.push(entryPointsSection);
      parts.push('');
    }
  }

  for (const section of sections) {
    parts.push(section.content);
    parts.push('');
  }

  // Only add placeholder if no project context was extracted
  const hasContext = metadata && (metadata.name || metadata.description || metadata.readmeSummary || metadata.keyDirectories.length > 0);
  if (!hasContext) {
    parts.push('## Project-Specific Notes');
    parts.push('');
    parts.push('<!-- Add project-specific context here: architecture decisions, key directories, dev workflow, etc. -->');
    parts.push('');
  }

  return {
    path: path.join(projectRoot, CLAUDE_MD),
    content: parts.join('\n'),
  };
}
